### ISSUE TITLE
Nastavak... iako još uvijek ne radi

### ISSUE THREAD

**Issue by lovrosverko** [MauroGiz/ZavrsniRad#1]
https://github.com/MauroGiz/ZavrsniRad/blob/6a8766f831e64162be500c6c5fbf8c39e03ded51/ProbaBaza/ProbaBaza/Form1.cs#L10

1. Treba instalirati MySQL Connector: https://dev.mysql.com/downloads/connector/net/6.1.html

2. Dodati reference u programu:
https://i.imgur.com/V0OF3RF.png 
https://i.imgur.com/dcUo0kf.png

Kod programa:
https://github.com/markom1/SmartCity/blob/master/WindowsFormsApp1/WindowsFormsApp1/Form1.cs

Moguće je da je problem na samoj bazi, ovo bi trebalo raditi.

**Comment by lovrosverko** [comment]
Sve radi, Raspberry je bio isključen. Dakle, prati korake 1 i 2 i nakon toga aplikacija radi kao urica. Spajaš se od bilo kuda na bazu podataka na Raspberry Pi koji je u školi, u IR.
Javi se da li ti je uspjelo.

marko.mijajlovic@sser.hr je čovjek iz 3.d koji radi na bazi pa se poveži s njim oko detalja što se tiče baze.

Slijedeće što trebaš je istražiti kako ćeš slati SQL naredbe bazi i povlačiti ili mijenjati podatke na bazi.

Čujemo se.

**Comment by MauroGiz** [comment]
Moze, moze, javljat cu vam kako mi ide rad. Hvala vam,
Lijep pozdrav

čet, 28. velj 2019. 22:29 Lovro Šverko <notifications@github.com> je
napisao:

**Comment by lovrosverko** [comment]
Nema na čemu. Najteže je odrađeno, sada slijedi "dosadan" dio.


Srdačan pozdrav,
Lovro Šverko, prof.



www.sser.hr

Srednja škola za elektrotehniku i računalstvo Rijeka
Zvonimirova 12
HR-51000



čet, 28. velj 2019. u 22:41 MauroGiz <notifications@github.com> napisao je:

**Comment by MauroGiz** [comment]
Poštovani prof. Šverko,

šaljem screen da mi je uspjelo povezivanje na bazu te sad moram nac nacin za upisivanje podataka, obradu i ispis.
![spojenaBaza](https://user-images.githubusercontent.com/35739412/54145098-8bbac100-442d-11e9-9d05-b6d6d97803ad.png)

Lijep pozdrav, 

Mauro Gizdulić
